
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# Example of Carbon beam in water tank.  Output is a 3D dose
# distribution map (with associated uncertainty) and map of producted
# C11.

#-------------------oooooOOOOO00000OOOOOooooo---------------------#


#=====================================================
# VERBOSE and VISUALISATION
#=====================================================

/control/execute mac/verbose.mac

# to use the visualisation :
#   - uncomment the following line
#   - use Gate --qt
#   - in the interface, type /control/execute mac/main.mac
/control/execute mac/visu.mac


#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase                 data/GateMaterials.db

# WORLD
/gate/world/setMaterial                      Air
/gate/world/geometry/setXLength              10.0 m
/gate/world/geometry/setYLength              10.0 m
/gate/world/geometry/setZLength              10.0 m

#Linac
/control/execute mac/linac_ion.mac

## Target : choose CT or waterbox
#/control/execute mac/target-CT.mac
#/control/execute mac/target-waterbox.mac

#======================

###  Generate materials from Hounsfield units
/gate/HounsfieldMaterialGenerator/SetMaterialTable                  data/Schneider2000MaterialsTable.txt
/gate/HounsfieldMaterialGenerator/SetDensityTable                   data/Schneider2000DensitiesTable.txt
/gate/HounsfieldMaterialGenerator/SetDensityTolerance               0.1 g/cm3
/gate/HounsfieldMaterialGenerator/SetOutputMaterialDatabaseFilename data/patient-HUmaterials.db
/gate/HounsfieldMaterialGenerator/SetOutputHUMaterialFilename       data/patient-HU2mat.txt
/gate/HounsfieldMaterialGenerator/Generate

###  Insert image

/gate/world/daughters/name                      target
/gate/world/daughters/insert                    ImageNestedParametrisedVolume
#/gate/world/daughters/insert                    ImageRegionalizedVolume

/gate/geometry/setMaterialDatabase              data/patient-HUmaterials.db
/gate/target/geometry/setHUToMaterialFile      data/patient-HU2mat.txt
/gate/target/geometry/setImage                 data/patient-4mm.mhd

/gate/target/placement/setTranslation 0. 0. 0. mm

### rotate the patient
/gate/target/placement/setRotationAxis 0 1 0
/gate/target/placement/setRotationAngle 90 deg


#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList QGSP_BERT_HP_EMY

/gate/physics/displayCuts
/gate/physics/print output/physics.txt

#=====================================================
# CUTS
#=====================================================

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      target 0.1 mm
/gate/physics/Electron/SetCutInRegion   target 0.1 mm
/gate/physics/Positron/SetCutInRegion   target 0.1 mm

/gate/physics/SetMaxStepSizeInRegion world 1 mm
/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter deuteron
/gate/physics/ActivateStepLimiter triton
/gate/physics/ActivateStepLimiter alpha
/gate/physics/ActivateStepLimiter GenericIon

/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter e-

# Verbose physic list (uncomment to display)
/gate/physics/displayCuts
# /gate/physics/processList Enabled
# /gate/physics/processList Initialized

#=====================================================
# OUTPUT - DETECTOR
#=====================================================

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat.txt
/gate/actor/stat/saveEveryNSeconds 60

# ----------------------------------------------------
# the following actor stores 3D distributions of
# dose/edep/uncertainty/nbHit into files (mhd image file format)

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  output/dose.mhd
/gate/actor/doseDistribution/attachTo    	   target
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 mm
/gate/actor/doseDistribution/setVoxelSize          2 2 2 mm
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableDose            true
/gate/actor/doseDistribution/enableSquaredDose     false
/gate/actor/doseDistribution/enableUncertaintyDose false
/gate/actor/doseDistribution/enableNumberOfHits    false
/gate/actor/doseDistribution/saveEveryNSeconds     20

/gate/actor/addActor ProductionAndStoppingActor    carbonMap
/gate/actor/carbonMap/save                         output/C11.mhd
/gate/actor/carbonMap/attachTo                     target
/gate/actor/carbonMap/stepHitType                  random
/gate/actor/carbonMap/setVoxelSize                 2 2 2 mm
/gate/actor/carbonMap/addFilter                    particleFilter
/gate/actor/carbonMap/particleFilter/addParticle   C11
/gate/actor/carbonMap/saveEveryNSeconds            20

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

#=====================================================
# BEAMS
#=====================================================

# Carbon 12 beam
#/gate/source/addSource               C12     gps
#/gate/source/C12/gps/particle        ion
#/gate/source/C12/gps/ion             6 12
#/gate/source/C12/gps/ene/type        Mono
#/gate/source/C12/gps/ene/mono        2314.24 MeV
#/gate/source/C12/gps/pos/type        Beam
#/gate/source/C12/gps/pos/shape       Circle
#/gate/source/C12/gps/halfx           2.0 mm
#/gate/source/C12/gps/halfy           2.0 mm
#/gate/source/C12/gps/pos/sigma_x     0.1 mm
#/gate/source/C12/gps/pos/sigma_y     0.1 mm
#/gate/source/C12/gps/ang/type        beam2d
#/gate/source/C12/gps/ang/sigma_x     0 deg
#/gate/source/C12/gps/ang/sigma_y     0 deg
#/gate/source/C12/gps/pos/centre      0.0 0.0 30.0  cm
#/gate/source/C12/gps/pos/centre       0.0 0.0 0.0  cm

# Proton beam
/gate/source/addSource                prot     gps
/gate/source/prot/gps/particle        proton

/gate/source/prot/gps/ene/type        Gauss
/gate/source/prot/gps/ene/mono        150 MeV
/gate/source/prot/gps/ene/sigma       10. MeV
/gate/source/prot/gps/ang/type        cos
/gate/source/prot/gps/ang/type        beam1d
/gate/source/prot/gps/ang/sigma_r     0. deg
/gate/source/prot/gps/pos/type        Beam
/gate/source/prot/gps/pos/shape       Circle
/gate/source/prot/gps/direction       0 0 1
/gate/source/prot/gps/pos/centre      0. 0. -500. cm
/gate/source/prot/gps/pos/radius      3. mm
/gate/source/prot/gps/pos/sigma_r     0.2 mm

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 1
/gate/application/start
